name: meta_weather_api
description: A Dart API Client for the MetaWeather API.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.1.0
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.1
